apiVersion: v1
kind: Service
metadata:  
  name: lbg-api-app-hayley
  labels:    
    app: lbg-api-app-hayley
spec:
  type: LoadBalancer
  selector:    
    app: lbg-api-app-hayley
  ports:  
  - port: 80    
    targetPort: 8080
